# This file contains common pin mappings for the 2018 Creality
# Ender 5 with an SKR mini e3 v1.2 and Bltouch v3.1

# note that you need to set serial settings to avoid auto-restart:
# stty -F /dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00 -hupcl

# bltouch 3.1 fix by Julien Lirochon:
# file: klippy/extras/bltouch.py -> search for function: def home_prepare(self)
# - inside this function, when you see : self.send_cmd(None)
# - replace with : self.send_cmd("touch_mode")

[stepper_x]
step_pin: PB13
dir_pin: !PB12
enable_pin: !PB14
step_distance: .0125
endstop_pin: ^PC0
position_endstop: 235
position_max: 235
homing_speed: 50

[tmc2209 stepper_x]
uart_pin: PB15
microsteps: 16
run_current: 0.580
hold_current: 0.500
stealthchop_threshold: 250

[stepper_y]
step_pin: PB10
dir_pin: !PB2
enable_pin: !PB11
step_distance: .0125
endstop_pin: ^PC1
position_endstop: 235
position_max: 235
homing_speed: 50

[tmc2209 stepper_y]
uart_pin: PC6
microsteps: 16
run_current: 0.580
hold_current: 0.500
stealthchop_threshold: 250

[stepper_z]
step_pin: PB0
dir_pin: !PC5
enable_pin: !PB1
step_distance: .0025
position_max: 300
endstop_pin: probe:z_virtual_endstop

[tmc2209 stepper_z]
uart_pin: PC10
microsteps: 16
run_current: 0.580
hold_current: 0.500
stealthchop_threshold: 5

[bltouch]
sensor_pin: ^PC2
control_pin: PA1
pin_move_time: 0.500
pin_up_reports_not_triggered: True
pin_up_touch_mode_reports_triggered: False
x_offset:-48
y_offset:-10
z_offset:2.675
speed:6
samples:1
sample_retract_dist:6
samples_result:average
#samples_tolerance:
#samples_tolerance_retries:

[extruder]
max_extrude_only_distance: 100.0
step_pin: PB3
dir_pin: !PB4
enable_pin: !PD2
step_distance: 0.00994
nozzle_diameter: 0.400
filament_diameter: 1.750
heater_pin: PC8
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PA0
control: pid
# tuned for stock hardware with 200 degree Celsius target
pid_Kp: 21.527
pid_Ki: 1.063
pid_Kd: 108.982
min_temp: 0
max_temp: 250
pressure_advance: 1.00

[tmc2209 extruder]
uart_pin: PC11
microsteps: 16
run_current: 0.650
hold_current: 0.500
stealthchop_threshold: 5

[heater_bed]
heater_pin: PC9
sensor_type: EPCOS 100K B57560G104F
sensor_pin: PC3
control: pid
# tuned for stock hardware with 50 degree Celsius target
pid_Kp: 54.027
pid_Ki: 0.770
pid_Kd: 948.182
min_temp: 0
max_temp: 75

[fan]
pin: PA8

[mcu]
serial: /dev/serial/by-id/usb-Klipper_Klipper_firmware_12345-if00

[printer]
kinematics: cartesian
max_velocity: 300
max_accel: 3000
max_z_velocity: 5
max_z_accel: 100

[static_digital_output usb_pullup_enable]
pins: !PC13

[board_pins]
aliases:
    # EXP1 header
    EXP1_1=PB5, EXP1_3=PA9,   EXP1_5=PA10, EXP1_7=PB8, EXP1_9=<GND>,
    EXP1_2=PB6, EXP1_4=<RST>, EXP1_6=PB9,  EXP1_8=PB7, EXP1_10=<5V>

[display]
lcd_type: st7920
cs_pin: EXP1_7
sclk_pin: EXP1_6
sid_pin: EXP1_8
encoder_pins: ^EXP1_5, ^EXP1_3
click_pin: ^!EXP1_2

[output_pin beeper]
pin: EXP1_1

[gcode_macro G29]
gcode:
        BLTOUCH_DEBUG COMMAND=reset
        G28
        G1 Z10 F600
        BED_MESH_CALIBRATE

[homing_override]
set_position_z:6
axes: z
gcode:
        G90
        G1 Z10 F6000
        G28 X Y
        G1 X163 Y117 F6000
        G28 Z0
        G1 X163 Y117 Z10

[bed_mesh]
horizontal_move_z: 6
min_point: 96,20
max_point: 230,230
probe_count: 4,4
speed: 150

[bed_screws]
screw1: 30,30
screw2: 200,30
screw3: 30,200
screw4: 200,200

[menu __main]
type: list
name: Main Menu
items:
    __tune
    __octoprint
    __control
    __temp
    __sdcard
    __filament
    __prepare

#[virtual_sdcard]
#path: ~/.octoprint/uploads/
